### ISSUE TITLE
Edges to be retained for graph model in dataloader.py

### ISSUE THREAD

**Issue by Chethan-Babu-stack** [SamitHuang/EV_GCN#3]
The function "def get_PAE_inputs(self, nonimg):" has a line "keep_ind = np.where(aff_score > 1.1)[0]". How did you come to the conclusion to retain edges whose edge value is more than 1.1 ?

**Comment by Chethan-Babu-stack** [comment]
I hope it is based on the number of non-imaging features considered. For instance, in the current code and dataset, there are 3 non-imaging features (site, age, gender). Given two patients, if there is more than 36.66% (1.1/3) of similarity, treat them as related, else not.

**Comment by Chethan-Babu-stack** [comment]
I hope it is based on the number of non-imaging features considered. For instance, in the current code and dataset, there are 3 non-imaging features (site, age, gender). Given two patients, if there is more than 36.66% (1.1/3) of similarity, treat them as related, else not.

**Comment by GreatnessBrain** [comment]
> he function "def get_PAE_inputs(self, nonimg):" has a line "keep_ind = np.where(aff_score > 1.1)[0]". How did you come to the conclusion to retain edges whose edge value is more than 1.1 ?

Hi, I have the same question as you. Do you know the answer now?  How did it come to the conclusion to retain edges whose edge value is more than 1.1?

**Comment by Chethan-Babu-stack** [comment]
I used two approaches:
1. **aff_score** was set to **zero**. Meaning, no pre-pruning of edges. The complete graph is fed in as an input and the GCN model will learn
2. **aff_score** was selected as a hyper-parameter and used **Optuna** framework to optimize it.

**Comment by GreatnessBrain** [comment]
Okay, I see.  Thank you for your answer！

**Comment by GreatnessBrain** [comment]
> I used two approaches:
> 
> 1. **aff_score** was set to **zero**. Meaning, no pre-pruning of edges. The complete graph is fed in as an input and the GCN model will learn
> 2. **aff_score** was selected as a hyper-parameter and used **Optuna** framework to optimize it.

Hi, Can you help me with another question? What is the purpose of the following code and what part of the article does it correspond to？Thanks a lot!

>         flatten_ind = 0 
>         for i in range(n):
>             for j in range(i+1, n):
>                 edge_index[:,flatten_ind] = [i,j]
>                 edgenet_input[flatten_ind]  = np.concatenate((nonimg[i], nonimg[j]))
>                 aff_score[flatten_ind] = aff_adj[i][j]  
>                 flatten_ind +=1
